### ISSUE TITLE
Download ARBORCLIP models

### ISSUE THREAD

**Issue by johnbradley** [BaskarGroup/arborclip.github.io#6]
The [Arboretum website](https://baskargroup.github.io/Arboretum/) mentions three models: ARBORCLIP-O, ARBORCLIP-B, and ARBORCLIP-M. Are these available for download from anywhere? Thanks.

**Comment by zahid-isu** [comment]
Thank you for your interest! You can download the ARBORCLIP models—ARBORCLIP-O, ARBORCLIP-B, and ARBORCLIP-M (updated name BioTrove-CLIP-O, BioTrove-CLIP-B, BioTrove-CLIP-M) from the HF model card. Here’s the link: https://huggingface.co/BGLab/BioTrove-CLIP

**Comment by zahid-isu** [comment]
Thank you for your interest! You can download the ARBORCLIP models—ARBORCLIP-O, ARBORCLIP-B, and ARBORCLIP-M (updated name BioTrove-CLIP-O, BioTrove-CLIP-B, BioTrove-CLIP-M) from the HF model card. Here’s the link: https://huggingface.co/BGLab/BioTrove-CLIP
